version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - static_data_debug:/app/staticfiles/
      - media_data_debug:/app/media/
    entrypoint:
      - /bin/sh
      - /app/docker/scripts/debug-server-entrypoint.sh
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data_debug:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${SQL_DB}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}

  redis:
    image: redis:7.2.5-alpine
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    restart: unless-stopped
    ports:
      - "63790:${REDIS_PORT}"

  rabbit:
    image: rabbitmq:3.13-management-alpine
    hostname: rabbit
    restart: always
    volumes:
      - rabbit_data_debug:/var/lib/rabbitmq/
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "56720:${RABBITMQ_NODE_PORT}"
      - "15682:${RABBITMQ_MANAGEMENT_PORT}"

  celery-worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: poetry run celery -A config worker --loglevel=info
    volumes:
      - static_data_debug:/app/staticfiles/
      - media_data_debug:/app/media/
    env_file:
      - .env
    depends_on:
      - rabbit
      - db

  flower:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: poetry run celery -A config flower 
      --address=0.0.0.0 
      --port=${FLOWER_PORT} 
      --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD} 
      --broker_api=${CELERY_BROKER_URL}/api
    volumes:
      - static_data_debug:/app/staticfiles/
      - media_data_debug:/app/media/
    env_file:
      - .env
    ports:
      - "55550:${FLOWER_PORT}"
    depends_on:
      - celery-worker

volumes:
  static_data_debug:
  media_data_debug:
  postgres_data_debug:
  rabbit_data_debug: